sapphiredev/plugins

packages/i18next/README.md, packages/i18next/src/index.ts, packages/i18next/src/lib/I18nextHandler.ts, packages/i18next/src/lib/types/context.ts, packages/i18next/src/register-discordjs.ts, packages/i18next/src/register.ts
This fixes the naming error previously found in i18next and also adds editing functionality.
CHANGES:
- `Message#sendTranslated` -> `Message#translated` (BREAKING)
- New optional argument for `Message#translated`: `edit` (boolean)
=> feat(i18next): implement context and editing

packages/i18next/src/index.ts, packages/i18next/src/lib/I18nextImplementation.ts, packages/i18next/src/lib/index.ts, packages/i18next/src/lib/types/client.ts, packages/i18next/src/lib/types/context.ts, packages/i18next/src/lib/types/implementations.ts, packages/i18next/src/lib/types/index.ts, packages/i18next/src/register-discordjs.ts, packages/i18next/src/register.ts
This does not change any functionality, however, documentation has been greatly improved, register
interfaces have been standardized, and instead of numerous re-implementations, mixins and factory
functions are now used. This makes augmenting any part of the plugin and implementing it with
various libraries in an agnostic way much easier and much more accessible, especially with the new
proper documentation.
=> refactor(i18next): docs and standardize implementation features

packages/api/package.json, packages/api/src/lib/structures/api/CookieStore.ts, yarn.lock
For Skyra the cookie is fetched for `api.skyra.pw` because that's where we have the API. However the websocket uses `box.skyra.pw`. Because these are different the browser ended up not sending the cookie with WebSocket requests, causing our backend to immediately `Unauthorized`. Looking at other cookies it actually had to be `.skyra.pw`. This fixes it.
Also should be noted that while `psl` in its current state is good enough, I opened a PR to the repo to improve it: https://github.com/lupomontero/psl/pull/273
=> fix(api): fixed how domain is retrieved for cookies

packages/subcommands/src/lib/SubCommandEntry.ts
Make subcommands case insensitive if the client has the option `caseInsensitiveCommands`.
=> fix(subcommands): respect caseInsensitive client option

packages/editable-commands/src/register.ts
Whenever running this plugin, I get the error:
```
C:\Users\xxx\OneDrive\Desktop\xxx\node_modules\@sapphire\plugin-editable-commands\dist\register.js:14
this.stores.get('listeners').registerPath(path_1.join(__dirname, 'listeners'));
^
TypeError: Cannot read property 'registerPath' of undefined
at SapphireClient.[SapphireFrameworkPluginsPreInitialization] (C:\Users\xxx\OneDrive\Desktop\xxx\node_modules\@sapphire\plugin-editable-commands\dist\register.js:14:37)
at new SapphireClient (C:\Users\xxx\OneDrive\Desktop\xxx\node_modules\@sapphire\framework\dist\lib\SapphireClient.js:83:25)
```
I believe this is because the `preInitialization` hook is triggered before the listener store (and all other stores) are registered. Quickly changing it to `post*` fixed the problem for me.
=> fix(editable-commands): register post initialization instead of pre-

package.json, packages/i18next/package.json, packages/i18next/src/lib/InternationalizationHandler.ts, yarn.lock
BREAKING CHANGE: i18next dependency has been bumped to v20.x. As opposed to what the library does, this plugin will default the new option `ignoreJSONStructure` to `false`
=> feat(i18next): bump i18next dependency to v20

packages/i18next/src/lib/InternationalizationHandler.ts, packages/i18next/src/lib/types.ts
This PR adds an option to the `InternationalizationOptions` called `formatters` which takes in a `I18nextFormatters` array to add to i18n via the `i18next.services.formatter.add` syntax, as described in https://www.i18next.com/translation-function/formatting#basic-usage.
Goal here is to move off the old, deprecated syntax and move to the new syntax, as the old way of adding formatters is considered deprecated in i18n version 21, described in https://www.i18next.com/translation-function/formatting#legacy-format-function-i18next-less-than-21.3.0.
=> feat(plugin-i18n): add new syntax for formatters in i18next

packages/scheduled-tasks/README.md
Added `along` to the line to make it clear that we are install `bull` as a dependency along with the package and not using `bull` as a package manager
=> chore(scheduled-tasks): make it clear that we are install bull as a dependency along with the package and not using bull as a package manager

packages/pattern-commands/src/index.ts, packages/pattern-commands/src/listeners/index.ts
There was an issue that in certain cases the index.ts in the listeners directory acted as a `PreCommandRunListener` clone.
This PR will fix it.
=> fix(pattern-commands): resolve listener triggering twice in rare cases

packages/scheduled-tasks/src/lib/ScheduledTaskHandler.ts, packages/scheduled-tasks/src/lib/strategies/ScheduledTaskRedisStrategy.ts, packages/scheduled-tasks/src/lib/strategies/ScheduledTaskSQSStrategy.ts, packages/scheduled-tasks/src/lib/types/ScheduledTaskBaseStrategy.ts
Adds 4 new methods:
1. [delete](https://github.com/OptimalBits/bull/blob/HEAD/REFERENCE.md#jobremove): Deletes/removes a job.
2. [list](https://github.com/OptimalBits/bull/blob/HEAD/REFERENCE.md#queuegetjobs): Lists jobs based on the type provided.
3. [listRepeated](https://github.com/OptimalBits/bull/blob/HEAD/REFERENCE.md#queuegetrepeatablejobs): Lists repeatable jobs.
4. [get](https://github.com/OptimalBits/bull/blob/HEAD/REFERENCE.md#queuegetjob): Get's a job of the id provided.
=> feat(scheduled-tasks): add `delete`, `list`, `listRepeated` & `get` methods

packages/scheduled-tasks/src/index.ts, packages/scheduled-tasks/src/lib/ScheduledTaskHandler.ts, packages/scheduled-tasks/src/lib/strategies/ScheduledTaskRedisStrategy.ts, packages/scheduled-tasks/src/lib/strategies/ScheduledTaskSQSStrategy.ts, packages/scheduled-tasks/src/lib/structures/ScheduledTask.ts, packages/scheduled-tasks/src/lib/types/ScheduledTaskBaseStrategy.ts, packages/scheduled-tasks/src/lib/types/ScheduledTaskEvents.ts, packages/scheduled-tasks/src/lib/types/ScheduledTasksOptions.ts, packages/scheduled-tasks/src/lib/types/index.ts
- fix(scheduled-tasks): fixed export of events enum not being on top level
- fix(scheduled-tasks): added tsdoc for `ScheduledTaskEvents`
- refactor(scheduled-tasks): use namespaced imports
- feat(scheduled-tasks): add getter for the client (So people can stop complaining about it)
- fix(scheduled-tasks): fixed the return types for the strategy methods
closes #210 (superseded)
=> Various fixes and a feature for scheduled tasks

packages/hmr/src/index.ts
This makes the `HMR plugin` logs more descriptive as they can be confusing, for example in cases like updating two pieces with the same name.
=> fix(hmr): improve logging

packages/i18next/src/register.ts
I have tested and it works fine without that event, and the problem with that event is that it is executed many times when starting the bot.
This happens when starting the bot with the "add" event of chokidar
=> perf(i18next): "add" event is not necessary in chokidar

packages/scheduled-tasks/src/lib/ScheduledTaskHandler.ts, packages/scheduled-tasks/src/lib/strategies/ScheduledTaskRedisStrategy.ts, packages/scheduled-tasks/src/lib/structures/ScheduledTask.ts, packages/scheduled-tasks/src/lib/types/ScheduledTasksTaskOptions.ts, packages/scheduled-tasks/src/register-redis.ts
My Redis store was getting filled with keys of failed tasks, turns out they can actually be removed by bull.
Control clicking takes me to `/register-redis` file where the module declaration is
And bull created it with the options correctly:
```json
{
"repeat": {
"count": 1,
"key": "__default__::::*/10 * * * *",
"cron": "*/10 * * * *"
},
"jobId": "repeat:521cc9772a578b272b59a27d7a892cd9:1642874400000",
"delay": 441492,
"timestamp": 1642873958508,
"prevMillis": 1642874400000,
"removeOnFail": true,
"removeOnComplete": true,
"attempts": 1
}
```
=> feat(scheduled-tasks): make it possible to configure additional Job options when using Redis strategy

packages/scheduled-tasks/src/lib/strategies/ScheduledTaskRedisStrategy.ts
By default the tasks were registered with the name "__ default __", so bull was confused by having tasks with the same name and overwrote them.
=> fix(schedules-tasks): create cron scheduled tasks with unique names to avoid name conflicts, causing tasks to be ignored

packages/i18next/src/lib/functions.ts, packages/i18next/src/lib/types.ts
- feat(i18next): add `guildLocale` and `locale` to `fetchLanguage` context
- fix(i18next): ensure an interaction is deferred or replied before editing
- fix(i18next): edit a reply when an already deferred or edited reply is passed into `replyLocalized`
Needs rebase & merge
=> Additional feature and 2 fixes for i18next

packages/pattern-commands/README.md
This PR updates the message intent deadline in the README of the pattern commands plugin to reflect the updated deadline:
https://support-dev.discord.com/hc/en-us/articles/4404772028055
=> docs(pattern-commands): update message intent deadline

packages/pattern-commands/src/lib/utils/PatternCommandInterfaces.ts, packages/pattern-commands/src/listeners/PluginCommandAccepted.ts
This PR adds the feature proposed in sapphiredev/framework#470 to the PatternCommands plugin as well
=> feat(plugin-pattern-commands): add success property to finished payload

packages/api/src/middlewares/headers.ts
This PR implements a fix for `plugin-api`.
Now, we first check if the route has a listener/handler for the `OPTIONS` type request and if the handler is present then let the custom handler execute. If no handler is present it still ends with `response.end()`.
=> fix: end response only if options route handler is not present

packages/scheduled-tasks/README.md, packages/scheduled-tasks/package.json, yarn.lock
They finally support ioredis version5, I don't know what else can describe how happy i am while opening this PR 😂
=> refactor(scheduled-task): remove `@types/ioredis`, require ioredis v5, and bump bullmq

packages/scheduled-tasks/package.json, packages/scheduled-tasks/register.d.ts, packages/scheduled-tasks/register.js, packages/scheduled-tasks/register.mjs, packages/scheduled-tasks/types-redis.js, packages/scheduled-tasks/types-redis.mjs
I'm in the process of creating my own custom strategy for this package.
However I faced a major problem: i obviously won't call `/register-redis`/`/register-sqs` obviously, so i have to call `/register` but it won't let me do it because it is not exposed! neither `@sapphire/plugin-scheduled-tasks/register`, nor `@sapphire/plugin-scheduled-tasks/dist/register` work.
This PR fixes that.
And also a little c/p mismatch I found in top-level `/types-redis`
=> fix(scheduled-tasks): various register fixes

packages/i18next/src/lib/functions.ts, packages/i18next/src/lib/types.ts
This PR ports applyLocalizedBuilder from @skyra/http-framework-i18n
I did also consider having a resolveLocale function which would convert locales like "ja-JP" to ones assignable to type LocaleString. (https://github.com/Arcadia148/plugins/blob/feat/localizedBuilders2/packages/i18next/src/lib/functions.ts#L189)
This PR closes #353
=> feat(plugin-i18next): add `applyLocalizedBuilder` and `createSelectMenuChoiceName` to help registering localized commands

packages/scheduled-tasks/README.md, packages/scheduled-tasks/package.json, packages/scheduled-tasks/src/lib/ScheduledTaskHandler.ts, packages/scheduled-tasks/src/lib/strategies/ScheduledTaskRedisStrategy.ts, packages/scheduled-tasks/src/lib/strategies/ScheduledTaskSQSStrategy.ts, packages/scheduled-tasks/src/lib/structures/ScheduledTask.ts, packages/scheduled-tasks/src/lib/structures/ScheduledTaskStore.ts, packages/scheduled-tasks/src/lib/types/ScheduledTasksTaskOptions.ts, yarn.lock
Closes #385 
Breaking change -
Cron option is removed, see - https://github.com/taskforcesh/bullmq/pull/1456
squash body:
```
BREAKING CHANGE: This plugin now depends on bullmq version 3.x. This means `cron` has been changed to `pattern`, see also https://github.com/taskforcesh/bullmq/pull/1456 and the full changelog https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/changelog.md#300-2022-10-25
```
=> refactor(scheduled-tasks)!: support for bullmq v3

packages/pattern-commands/src/lib/structures/PatternCommand.ts, packages/pattern-commands/src/lib/utils/PatternCommandInterfaces.ts, packages/pattern-commands/src/listeners/PluginCommandAccepted.ts, packages/pattern-commands/src/listeners/PluginMessageParse.ts, packages/pattern-commands/src/listeners/PluginPreCommandRun.ts
With this feature users can add a weight to the `patternCommand` which can influence which one should run if more than one is found in the given message.
For example if `message.content` is "Split up and search for clues" and there's a `patternCommand-search` with the weight of 3 and `patternCommand-clue` with weight of 7, the `patternCommand-clue` will run
BUT if the preconditions doesn't allow `patternCommand-clue` to run, `patternCommand-search` will run instead (if the preconditions are allowing it)
=> feat(plugin-patterncommands): add command weight and allow to run another patternCommand if one was caught by a precondition

packages/subcommands/src/lib/Subcommand.ts
This PR changes the behavior of the `supportsMessageCommands()` and `supportsChatInputCommands()` methods on the subcommand class. Previously, these both would always return true since the methods inherited from the `Command` class just check for the existence of a `messageRun()` or `chatInputRun()` method. Since both methods are implemented on the `Subcommand` class, the type guards would always return true. This PR instead determines the output of these methods by checking if a `messageRun` or  `chatInputRun` property was provided on any of the subcommands in the `parsedSubcommandMappings` array. These changes were tested using commands with all combinations of having a messageRun, having a chatInputRun, having both, having groups, and not having groups. Test commands can be found [in …
=> fix: supportsXCommands() methods now use SubcommandMappings

package.json, packages/api/package.json, packages/api/src/lib/structures/Augmentations.d.ts, packages/api/src/lib/structures/http/Auth.ts, packages/api/src/routes/oauth/callback.ts, packages/api/src/routes/oauth/logout.ts, yarn.lock
Follow up to https://github.com/sapphiredev/plugins/pull/143 (and https://github.com/discordjs/discord.js/pull/6586)
=> refactor: node-fetch to undici

packages/api/src/lib/structures/http/HttpCodes.ts, packages/api/src/lib/structures/http/Server.ts, packages/api/src/lib/utils/MimeTypes.ts, packages/api/src/lib/utils/RouteData.ts, packages/logger/src/lib/LoggerStyle.ts
`const enum` is not available when option `verbatimModuleSyntax` is enabled in TS 5.x.
By removing `const`, it makes enum available in TS 5.x with `verbatimModuleSyntax`.
=> fix: remove const enum for verbatimModuleSyntax

packages/scheduled-tasks/src/lib/types/ScheduledTaskEvents.ts
Types for events were previously just comments on the `ScheduledTaskEvents` enum. Now the types can be properly enforced for emitters and listeners.
=> feat(scheduled-tasks): add typings for listener events

packages/api/src/lib/structures/api/ApiResponse.ts, packages/api/src/lib/utils/MimeTypes.ts
I added the `text/html` mimetype, so that it is now possible to send html in api routes. This is also used in the new `ApiResponse.html()` function which is a shortcut similar to `ApiResponse.json()` and `ApiResponse.text()`.
I also added the `image/x-icon` mimetype in order to implement an endpoint for favicon.ico :)
Another idea would be to make the favicon a configuration option (providing a buffer / image path?), so that we don't have to manually create a route for it. But that's just inspiration, I'm not sure how many people would want to use it / if you want that in the options :)
=> feat(api): add `text/html` and `image/x-icon` mime types

packages/logger/src/lib/Logger.ts
`process.stdout` and `process.stderr` are both `WriteStream`, which has the following inheritance:
- `NodeJS.WriteStream` extends `tty.WriteStream`
- `tty.WriteStream` extends `net.Socket`
- `net.Socket` extends `stream.Duplex`
- `stream.Duplex` extends `stream.Readable` implements `stream.Writable`
- `stream.Writable` extends `Stream` implements `NodeJS.WritableStream`
*Not a breaking change, yay!* 🎉
This commit generalizes the `stdout` and `stderr` types to `NodeJS.WritableStream` to allow for more flexibility and match the types in `Console`'s constructor arguments.
I don't know why `NodeJS.WriteStream`, being such a generic name, has such a deep inheritance that extends `Duplex`, which is also readable, but here we are. `NodeJS.WritableStream` is the most generic type that can be used …
=> refactor: generalize `stdout` and `stderr` types

packages/subcommands/src/lib/Subcommand.ts, packages/subcommands/src/lib/SubcommandMappings.ts
This is to match https://github.com/sapphiredev/framework/pull/655 because it's far easier for users to say `runIn: ChannelTypes.DM` than `preconditions: [{ name: 'ChannelPreConditions.RunIn, context: { type: ChannelTypes.DM }}]`
=> feat(subcommands): add runIn to match framework

packages/i18next/src/index.ts, packages/i18next/src/register.ts
Same as #471 but now pushing it through I guess for the sake of consistency with other plugins. That said, this won't fix the actual augmentation issues that #471 was supposedly meant to fix as those were and are still related to TS 5.2 in combination with @sapphire/ts-config v4 or not using
```json
"module": "node16",
"moduleResolution": "node16"
```
=> fix(i18next): move module augmentations to `index` and import in `register`

packages/i18next/src/lib/functions.ts
The value passed to the`resolveKey ` function was incorrect, resulting in errors every time it was called. 
This PR corrects this problem.
=> fix(i18next): fixed `resolveKey` using incorrect paramater when no default value is passed through

packages/scheduled-tasks/src/index.ts, packages/scheduled-tasks/src/listeners/connectError.ts, packages/scheduled-tasks/src/listeners/error.ts, packages/scheduled-tasks/src/listeners/notFound.ts, packages/scheduled-tasks/src/register.ts
This PR adds default error listeners to the scheduled-tasks plugin. They are **not** enabled by default.
Currently if a connection error is thrown in the `ScheduledTaskHandler` constructor, it gets emitted to a listener instead of showing in stderr. So if there if no listener for that event an error will never be shown, which is not fun for debugging.
Reference: https://discord.com/channels/737141877803057244/737142940777971773/1170749988918272063
=> feat(scheduled-tasks): add error listeners

packages/i18next/src/index.ts
Re-exporting the `i18next` instance is particularly useful in some concrete cases, such as registering plugins of any kind or having access to many of the [`I18n`](https://www.i18next.com/overview/api)'s methods.
Doing `import i18next from 'i18next';` isn't a portable solution. Currently, if `@sapphire/plugin-i18next` is imported, it'll always use the CJS version of `i18next`[^1], as the library is built into CJS with ESM bindings[^2].
[^1]: https://github.com/i18next/i18next/blob/2a7e478b6b7635ebd5505261ae0064dcf41116b4/package.json#L15-L22
[^2]: https://github.com/sapphiredev/plugins/blob/95fe74c44ccae490710923cb4d25d45b13ff4030/packages/i18next/package.json#L30-L32
=> feat: re-export `i18next` instance

packages/scheduled-tasks/src/lib/ScheduledTaskHandler.ts, packages/scheduled-tasks/src/lib/structures/ScheduledTask.ts, packages/scheduled-tasks/src/lib/types/ScheduledTaskTypes.ts
This PR adds timezone support for pattern tasks.
The Changes in this PR would not constitute a breaking change.
=> feat(scheduled-tasks): add timezone for tasks with pattern

packages/scheduled-tasks/UPGRADING-v9-v10.md, packages/scheduled-tasks/package.json, packages/scheduled-tasks/src/index.ts, packages/scheduled-tasks/src/lib/ScheduledTaskHandler.ts, packages/scheduled-tasks/src/lib/types/ScheduledTaskTypes.ts, yarn.lock
This PR bumps the BullMQ dependency for the scheduled-tasks plugin to version `5.1.0`.
Additionally, it makes the `tasks` client property required as a connection string will always be needed.
=> feat: bullmq v5

packages/subcommands/src/index.ts, packages/subcommands/src/lib/precondition-resolvers/subcommandCooldown.ts, packages/subcommands/src/lib/types/Enums.ts, packages/subcommands/src/preconditions/PluginSubcommandCooldown.ts
So technically this would be a breaking change due to the rename in the constant at top level but since it never really worked before I'd say we can push it as a semver:patch.
Reported in https://discord.com/channels/737141877803057244/1190424789043658822
=> fix(plugins): fixed name for plugin subcommnad cooldown precondition

packages/i18next/src/lib/InternationalizationHandler.ts
@kyranet and I noticed this in Skyra. Why no other Sapphire users reported this as a bug is truly beyond me. 
Despite i18next happily accepting 3 parameters, in actuality, it's supposed to be just 2 with the `defaultValue` being part of an object as the second parameter. I think I didn't write it like this initially because without the `as TOpt` type cast an error is thrown due to a type mismatch with the generic types but that is easily resolved then.
I also added some more function generic type defaults to match that of `resolveKey` and this way it should allow `format` to smartly return a `string` whereas before it would always, as far as types were concerned, return an object.
=> fix: fixed container.format not processing variables correctly

packages/api/src/lib/structures/Route.ts, packages/api/src/lib/utils/RouteData.ts
- 🚀 Add filesystem-based path definition fallback for routes (fixes #583)
- 🚀 Add re-exports for `ApiRequest` and `ApiResponse` in the `Route` namespace
- 🏠 Refactor `RouteData` slightly to make the code more readable and easier to maintain
- 🔥 **BREAKING CHANGE:** The prefix is now suffixed with a `/` before concatenating in `RouteData` (supersedes #582, sorry Favna)
- 🔥 **BREAKING CHANGE:** `Route` now reads defaults to filesystem-based path definition when `options.route` is not defined. Virtual pieces (those loaded with `loadPiece`) are unaffected
- 🔥 **BREAKING CHANGE:** Route parameters are now defined as `/guilds/[guild]` rather than `/guilds/:guild`
👀
=> refactor(route)!: proper route handling and FS-based paths

packages/api/src/lib/structures/MediaParser.ts, packages/api/src/lib/structures/Middleware.ts, packages/api/src/lib/structures/MiddlewareStore.ts, packages/api/src/lib/structures/Route.ts, packages/api/src/lib/structures/RouteLoaderStrategy.ts, packages/api/src/lib/structures/RouteStore.ts, packages/api/src/lib/structures/api/CookieStore.ts, packages/api/src/lib/structures/http/HttpMethods.ts, packages/api/src/lib/structures/http/Server.ts, packages/api/src/listeners/PluginServerMatch.ts, packages/api/src/listeners/PluginServerMiddlewareSuccess.ts, packages/api/src/listeners/PluginServerRequest.ts, packages/api/src/mediaParsers/applicationJson.ts, packages/api/src/mediaParsers/textPlain.ts, packages/api/src/middlewares/auth.ts, packages/api/src/middlewares/body.ts, packages/api/src/middlewares/cookies.ts, packages/api/src/middlewares/headers.ts, packages/api/src/routes/_load.ts, packages/api/src/routes/oauth/callback.post.ts, packages/api/src/routes/oauth/logout.post.ts
- 🚀 Added support for specifying a route's supported methods in the options
- 🚀 Added support for specifying a route's method in the file name
- ⌨️ Added `MediaParser.Request` and `MediaParser.Response` type aliases
- ⌨️ Added `Middleware.Request` and `Middleware.Response` type aliases
- 🏠 Hardened the `onLoad` and `onUnload` hooks from the `Route` class
- 🔥 **BREAKING CHANGE:** The headers middleware now uses the supported HTTP methods from the route or the store instead of sending all supported methods
- 🔥 **BREAKING CHANGE:** Changed the method handling in the `Route` class to not be keyed by the method name, sending all requests to the `run` method. This allows for more flexibility in the route handling
- 🔥 **BREAKING CHANGE:** Writing the name of a file as `<name>.<method>.ts` will …
=> refactor(route)!: change method handling

packages/subcommands/src/lib/Subcommand.ts, packages/subcommands/src/lib/types/Events.ts, packages/subcommands/src/listeners/PluginChatInputSubcommandNoMatch.ts, packages/subcommands/src/listeners/PluginMessageSubcommandNoMatch.ts, packages/subcommands/src/listeners/_load.ts
Fixes #600
```md
BREAKING CHANGE: Previously if no subcommand matched the error was emitted to `MessageCommandError` or `ChatInputCommandError`. This was inconsistent with errors during runtime being emitted to `MessageSubcommandError` and `ChatInputSubcommandError` respectively. Therefore these events are now emitted to the new events `PluginMessageSubcommandNoMatch` and `PluginChatInputSubcommandNoMatch` respectively. There are new built-in listeners for these events that will log the infractions to the console at error level. You can override these listeners to provide your own functionality.
```
=> refactor: changed no match errors to emit on a subcommand listener instead of the root MessageCommandError / ChatInputCommandError

packages/scheduled-tasks/README.md
I have removed the duplication in the README file of the scheduled tasks plugin.
=> docs(readme): remove duplication in Scheduled Tasks README

packages/api/src/lib/structures/Route.ts, packages/api/src/lib/structures/router/RouterRoot.ts
This allows for grouping routes together in the router:
```ts
-| routes/
---| information.get.ts
---| (legal)/
-----| license.get.ts
-----| privacy.get.ts
```
This will produce the following routes:
- `GET /information`
- `GET /license`
- `GET /privacy`
The `legal` group is ignored for purposes of the
route URL path.
=> feat(router): add FS group syntax

packages/subcommands/src/lib/types/SubcommandMappings.ts
This fixes the example provided for `messageRun` in the `packages/subcommands/src/lib/types/SubcommandMappings.ts` file.
=> docs(SubcommandMappings): fix messageRun example

packages/api/src/register.ts
Somehow the index import with the merged types for the api plugin ended up decoupled from the plugin register file; without it, the client constructor will not take any configuration settings for the api plugin and the container will not have the server object. This PR restores the import to the same state as the other plugins in the repo.
The current workaround is to import both the index and register file to get the ambient declarations to be detected by TypeScript again which seems unintentional.
```ts
// One of these is not like the others...
import '@sapphire/plugin-api/register';
import '@sapphire/plugin-api';
import '@sapphire/plugin-logger/register';
import '@sapphire/plugin-i18next/register';
```
=> fix(api): revert removing index import for api plugin register file
